version: "3"
services:
  app:
    container_name: trivia_game_app
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/trivia-game
      - /var/www/trivia-game/node_modules